-- ============================ --
--   PSDB [vehicle_accessory]   --
-- ============================ --

ALTER TABLE `vehicle_accessory` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

UPDATE `vehicle_accessory` SET `description`='Destrero de la muerte de Acherus' WHERE `entry`=28782 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Máquina de asedio de Conquista del Invierno' WHERE `entry`=28312 AND `seat_id`=7;
UPDATE `vehicle_accessory` SET `description`='Máquina de asedio de Conquista del Invierno' WHERE `entry`=32627 AND `seat_id`=7;
UPDATE `vehicle_accessory` SET `description`='Kologarn' WHERE `entry`=32930 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Kologarn' WHERE `entry`=32930 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Demoledor recuperado' WHERE `entry`=33109 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Máquina de asedio recuperada' WHERE `entry`=33060 AND `seat_id`=7;
UPDATE `vehicle_accessory` SET `description`='Leviatán de llamas' WHERE `entry`=33113 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Leviatán de llamas' WHERE `entry`=33113 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Leviatán de llamas' WHERE `entry`=33113 AND `seat_id`=2;
UPDATE `vehicle_accessory` SET `description`='Leviatán de llamas' WHERE `entry`=33113 AND `seat_id`=3;
UPDATE `vehicle_accessory` SET `description`='Leviatán de llamas' WHERE `entry`=33113 AND `seat_id`=7;
UPDATE `vehicle_accessory` SET `description`='Profesor Putricidio' WHERE `entry`=36678 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Mecacóptero 304-A' WHERE `entry`=33214 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Montura del mariscal Jacob Alerius' WHERE `entry`=35637 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Ambrose Chisparrayo' WHERE `entry`=35633 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Colosos' WHERE `entry`=35768 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Jaelyne Unicanto' WHERE `entry`=34658 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Lana Martillotenaz' WHERE `entry`=35636 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Mokra el Trituracráneos' WHERE `entry`=35638 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Eressea Cantoalba' WHERE `entry`=35635 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Runok Ferocrín' WHERE `entry`=35640 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Zul\'tore' WHERE `entry`=35641 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura del mortacechador Visceri' WHERE `entry`=35634 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Grifo resucitado' WHERE `entry`=27241 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Grifo de Hibergarde' WHERE `entry`=27661 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Raptor de Drakuru' WHERE `entry`=29698 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Hipogrifo de torneo' WHERE `entry`=33778 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Yertafauce' WHERE `entry`=33687 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Yertafauce' WHERE `entry`=33687 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Yertafauce' WHERE `entry`=33687 AND `seat_id`=2;
UPDATE `vehicle_accessory` SET `description`='Protodraco de El Encuentro Hyldnir' WHERE `entry`=29625 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Protodraco de Jotunheim' WHERE `entry`=30330 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Avión de caza Rompecielo' WHERE `entry`=32189 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Profesor Putricidio' WHERE `entry`=36678 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Mamut de tundra de viajero' WHERE `entry`=32640 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Mamut de tundra de viajero' WHERE `entry`=32640 AND `seat_id`=2;
UPDATE `vehicle_accessory` SET `description`='Mamut de tundra de viajero' WHERE `entry`=32633 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Mamut de tundra de viajero' WHERE `entry`=32633 AND `seat_id`=2;
UPDATE `vehicle_accessory` SET `description`='Ingeniero del Demoledor Llavestruendo' WHERE `entry`=33669 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Zapador goblin' WHERE `entry`=29555 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Thiassi el Liberador de Rayos' WHERE `entry`=28018 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Suertudo Wilhelm' WHERE `entry`=28054 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Lobo de Orgrimmar' WHERE `entry`=33409 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Kodo de Cima del Trueno' WHERE `entry`=33300 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Carnero de Forjaz' WHERE `entry`=33408 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Mecazancudo de Gnomeregan' WHERE `entry`=33301 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Caballo de guerra Renegado' WHERE `entry`=33414 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Corcel de Ventormenta' WHERE `entry`=33297 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Elekk de El Exodar' WHERE `entry`=33416 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Sable de la noche darnassiano' WHERE `entry`=33298 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Elekk de El Exodar' WHERE `entry`=33318 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Sable de la noche darnassiano' WHERE `entry`=33319 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Carnero de Forjaz' WHERE `entry`=33316 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Mecazancudo de Gnomeregan' WHERE `entry`=33317 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Corcel de Ventormenta' WHERE `entry`=33217 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Caballo de guerra Renegado' WHERE `entry`=33324 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Kodo de Cima del Trueno' WHERE `entry`=33322 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Lobo de Orgrimmar' WHERE `entry`=33320 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Halcón zancudo de Lunargenta' WHERE `entry`=33323 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Raptor Lanza Negra' WHERE `entry`=33321 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Halcón zancudo de Lunargenta' WHERE `entry`=33418 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Raptor Lanza Negra' WHERE `entry`=33299 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Grifo esquelético del Caballero Negro' WHERE `entry`=35491 AND `seat_id`=0;
