-- ===================== --
--   PSDB [game_event]   --
-- ===================== --

ALTER TABLE `game_event` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

UPDATE `game_event` SET `description`='Festival de Solsticio' WHERE `entry`='1';
UPDATE `game_event` SET `description`='Festival de Invierno' WHERE `entry`='2';
UPDATE `game_event` SET `description`='Feria de la Luna Negra (Bosque de Terokkar)' WHERE `entry`='3';
UPDATE `game_event` SET `description`='Feria de la Luna Negra (Bosque de Elwynn)' WHERE `entry`='4';
UPDATE `game_event` SET `description`='Feria de la Luna Negra (Mulgore)' WHERE `entry`='5';
UPDATE `game_event` SET `description`='Año Nuevo' WHERE `entry`='6';
UPDATE `game_event` SET `description`='Festival Lunar' WHERE `entry`='7';
UPDATE `game_event` SET `description`='Amor en el Aire' WHERE `entry`='8';
UPDATE `game_event` SET `description`='Jardín Noble' WHERE `entry`='9';
UPDATE `game_event` SET `description`='Semana de los Niños' WHERE `entry`='10';
UPDATE `game_event` SET `description`='Festival de la Cosecha' WHERE `entry`='11';
UPDATE `game_event` SET `description`='Halloween' WHERE `entry`='12';
UPDATE `game_event` SET `description`='Invasión de Elementales' WHERE `entry`='13';
UPDATE `game_event` SET `description`='Va a comenzar la Fiesta de la Pesca en Tuercespina' WHERE `entry`='14';
UPDATE `game_event` SET `description`='Fiesta de la Pesca en Tuercespina' WHERE `entry`='15';
UPDATE `game_event` SET `description`='Captura del Botín en Gurubashi Arena' WHERE `entry`='16';
UPDATE `game_event` SET `description`='Invasión de la Plaga' WHERE `entry`='17';
UPDATE `game_event` SET `description`='Llamamiento a las Armas: Valle de Alterac' WHERE `entry`='18';
UPDATE `game_event` SET `description`='Llamamiento a las Armas: Garganta Grito de Guerra' WHERE `entry`='19';
UPDATE `game_event` SET `description`='Llamamiento a las Armas: Cuenca de Arathi' WHERE `entry`='20';
UPDATE `game_event` SET `description`='Llamamiento a las Armas: Ojo de la Tormenta' WHERE `entry`='21';
UPDATE `game_event` SET `description`='Refuerzos para Anh Qiraj' WHERE `entry`='22';
UPDATE `game_event` SET `description`='Edificio de la Feria de la Luna Negra (Bosque de Elwynn)' WHERE `entry`='23';
UPDATE `game_event` SET `description`='¡Festival de la Cerveza!' WHERE `entry`='26';
UPDATE `game_event` SET `description`='Anochece' WHERE `entry`='27';
UPDATE `game_event` SET `description`='Jardín Noble' WHERE `entry`='28';
UPDATE `game_event` SET `description`='Locura de Espadas, Gri\'lek' WHERE `entry`='29';
UPDATE `game_event` SET `description`='Locura de Espadas, Hazza\'rah' WHERE `entry`='30';
UPDATE `game_event` SET `description`='Locura de Espadas, Renataki' WHERE `entry`='31';
UPDATE `game_event` SET `description`='Locura de Espadas, Wushoolay' WHERE `entry`='32';
UPDATE `game_event` SET `description`='Torneo de Arenas' WHERE `entry`='33';
UPDATE `game_event` SET `description`='Concierto de los L70ETC en Bosque Terokkar' WHERE `entry`='34';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 1 - Reclamando el Sagrario' WHERE `entry`='35';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 1 - Reclamando el Sagrario COMPLETA' WHERE `entry`='36';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 2 - Arsenal de Tramo del Sol' WHERE `entry`='37';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 2 - Arsenal de Tramo del Sol COMPLETA' WHERE `entry`='38';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 2b - Activando el Portal de La Fuente del Sol' WHERE `entry`='39';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 2b - Activando el Portal de La Fuente del Sol COMPLETA' WHERE `entry`='40';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 3 - Puerto de Tramo del Sol' WHERE `entry`='41';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 3 - Puerto de Tramo del Sol COMPLETA' WHERE `entry`='42';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 3b - Reconstruyendo el Yunque y la Forja' WHERE `entry`='43';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 3b - Reconstruyendo el Yunque y la Forja COMPLETA' WHERE `entry`='44';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 4A - Creando el Laboratorio de Alquímia' WHERE `entry`='45';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 4A - Creando el Laboratorio de Alquímia COMPLETA' WHERE `entry`='46';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 4B - Construyendo el Monumento a los Caídos' WHERE `entry`='47';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 4B - Construyendo el Monumento a los Caídos COMPLETA' WHERE `entry`='48';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 4 - COMPLETA' WHERE `entry`='49';
UPDATE `game_event` SET `description`='La Defensa de la Alianza de Conquista del Invierno' WHERE `entry`='50';
UPDATE `game_event` SET `description`='La Defensa de la Horda de Conquista del Invierno' WHERE `entry`='51';
UPDATE `game_event` SET `description`='Festival de Invierno: Regalos' WHERE `entry`='54';
UPDATE `game_event` SET `description`='Se busca: La gema de alma del exarca' WHERE `entry`='100';
UPDATE `game_event` SET `description`='Se busca: Fusta de montar de Nazan' WHERE `entry`='101';
UPDATE `game_event` SET `description`='Se busca: El amuleto maravilloso de Shaffar' WHERE `entry`='102';
UPDATE `game_event` SET `description`='Se busca: La cabeza del cazador de Época' WHERE `entry`='103';
UPDATE `game_event` SET `description`='Se busca: Las plumas del tocado de Ikiss' WHERE `entry`='104';
UPDATE `game_event` SET `description`='Se busca: El susurro de Murmullo' WHERE `entry`='105';
UPDATE `game_event` SET `description`='Se busca: El pergamino de Cieloriss' WHERE `entry`='106';
UPDATE `game_event` SET `description`='Se busca: El báculo con plumas de Keli\'dan' WHERE `entry`='107';
UPDATE `game_event` SET `description`='Se busca: El proyector de Pathaleon' WHERE `entry`='108';
UPDATE `game_event` SET `description`='Se busca: El corazón de Quagmirran' WHERE `entry`='109';
UPDATE `game_event` SET `description`='Se busca: El Tratado del Señor de la Guerra' WHERE `entry`='110';
UPDATE `game_event` SET `description`='Se busca: Un huevo de acechadora negra' WHERE `entry`='111';
UPDATE `game_event` SET `description`='Se busca: El reloj de Arena de Aeonus' WHERE `entry`='112';
UPDATE `game_event` SET `description`='Se busca: Un esqueje de disidente de distorsión' WHERE `entry`='113';
UPDATE `game_event` SET `description`='Se busca: El sello de Garrafilada' WHERE `entry`='114';
UPDATE `game_event` SET `description`='Se busca: El sello del príncipe Kael\'thas' WHERE `entry`='115';
UPDATE `game_event` SET `description`='Se busca: Mirmidones Colmillo Torcido' WHERE `entry`='116';
UPDATE `game_event` SET `description`='Se busca: Centuriones Mano Destrozada' WHERE `entry`='117';
UPDATE `game_event` SET `description`='Se busca: Destructores de Forja de Tempestad' WHERE `entry`='118';
UPDATE `game_event` SET `description`='Se busca: Canalizadores Buscasol' WHERE `entry`='119';
UPDATE `game_event` SET `description`='Se busca: Señores de la falla' WHERE `entry`='120';
UPDATE `game_event` SET `description`='Se busca: Centinelas de Arcatraz' WHERE `entry`='121';
UPDATE `game_event` SET `description`='Se busca: Instructoras maliciosas' WHERE `entry`='122';
UPDATE `game_event` SET `description`='Se busca: Hermanas del Tormento' WHERE `entry`='123';
UPDATE `game_event` SET `description`='Llamamiento a las armas: Playa de los Ancestros' WHERE `entry`='124';
UPDATE `game_event` SET `description`='Llamamiento a las armas: Isla de la Conquista' WHERE `entry`='125';
UPDATE `game_event` SET `description`='Arenas Temporada 3' WHERE `entry`='126';
UPDATE `game_event` SET `description`='Arenas Temporada 4' WHERE `entry`='127';
UPDATE `game_event` SET `description`='Arenas Temporada 5' WHERE `entry`='128';
UPDATE `game_event` SET `description`='Arenas Temporada 6' WHERE `entry`='129';
UPDATE `game_event` SET `description`='Arenas Temporada 7' WHERE `entry`='130';
UPDATE `game_event` SET `description`='Arenas Temporada 8' WHERE `entry`='131';
