-- ===================== --
--   PSDB [game_event]   --
-- ===================== --

ALTER TABLE `game_event` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

UPDATE `game_event` SET `description`='Festival de Solsticio' WHERE `EventEntry`='1';
UPDATE `game_event` SET `description`='Festival de Invierno' WHERE `EventEntry`='2';
UPDATE `game_event` SET `description`='Feria de la Luna Negra (Bosque de Terokkar)' WHERE `EventEntry`='3';
UPDATE `game_event` SET `description`='Feria de la Luna Negra (Bosque de Elwynn)' WHERE `EventEntry`='4';
UPDATE `game_event` SET `description`='Feria de la Luna Negra (Mulgore)' WHERE `EventEntry`='5';
UPDATE `game_event` SET `description`='Año Nuevo' WHERE `EventEntry`='6';
UPDATE `game_event` SET `description`='Festival Lunar' WHERE `EventEntry`='7';
UPDATE `game_event` SET `description`='Amor en el Aire' WHERE `EventEntry`='8';
UPDATE `game_event` SET `description`='Jardín Noble' WHERE `EventEntry`='9';
UPDATE `game_event` SET `description`='Semana de los Niños' WHERE `EventEntry`='10';
UPDATE `game_event` SET `description`='Festival de la Cosecha' WHERE `EventEntry`='11';
UPDATE `game_event` SET `description`='Halloween' WHERE `EventEntry`='12';
UPDATE `game_event` SET `description`='Invasión de Elementales' WHERE `EventEntry`='13';
UPDATE `game_event` SET `description`='Va a comenzar la Fiesta de la Pesca en Tuercespina' WHERE `EventEntry`='14';
UPDATE `game_event` SET `description`='Fiesta de la Pesca en Tuercespina' WHERE `EventEntry`='15';
UPDATE `game_event` SET `description`='Captura del Botín en Gurubashi Arena' WHERE `EventEntry`='16';
UPDATE `game_event` SET `description`='Invasión de la Plaga' WHERE `EventEntry`='17';
UPDATE `game_event` SET `description`='Llamamiento a las Armas: Valle de Alterac' WHERE `EventEntry`='18';
UPDATE `game_event` SET `description`='Llamamiento a las Armas: Garganta Grito de Guerra' WHERE `EventEntry`='19';
UPDATE `game_event` SET `description`='Llamamiento a las Armas: Cuenca de Arathi' WHERE `EventEntry`='20';
UPDATE `game_event` SET `description`='Llamamiento a las Armas: Ojo de la Tormenta' WHERE `EventEntry`='21';
UPDATE `game_event` SET `description`='Refuerzos para Anh Qiraj' WHERE `EventEntry`='22';
UPDATE `game_event` SET `description`='Edificio de la Feria de la Luna Negra (Bosque de Elwynn)' WHERE `EventEntry`='23';
UPDATE `game_event` SET `description`='¡Festival de la Cerveza!' WHERE `EventEntry`='26';
UPDATE `game_event` SET `description`='Anochece' WHERE `EventEntry`='27';
UPDATE `game_event` SET `description`='Jardín Noble' WHERE `EventEntry`='28';
UPDATE `game_event` SET `description`='Locura de Espadas, Gri\'lek' WHERE `EventEntry`='29';
UPDATE `game_event` SET `description`='Locura de Espadas, Hazza\'rah' WHERE `EventEntry`='30';
UPDATE `game_event` SET `description`='Locura de Espadas, Renataki' WHERE `EventEntry`='31';
UPDATE `game_event` SET `description`='Locura de Espadas, Wushoolay' WHERE `EventEntry`='32';
UPDATE `game_event` SET `description`='Torneo de Arenas' WHERE `EventEntry`='33';
UPDATE `game_event` SET `description`='Concierto de los L70ETC en Bosque Terokkar' WHERE `EventEntry`='34';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 1 - Reclamando el Sagrario' WHERE `EventEntry`='35';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 1 - Reclamando el Sagrario COMPLETA' WHERE `EventEntry`='36';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 2 - Arsenal de Tramo del Sol' WHERE `EventEntry`='37';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 2 - Arsenal de Tramo del Sol COMPLETA' WHERE `EventEntry`='38';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 2b - Activando el Portal de La Fuente del Sol' WHERE `EventEntry`='39';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 2b - Activando el Portal de La Fuente del Sol COMPLETA' WHERE `EventEntry`='40';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 3 - Puerto de Tramo del Sol' WHERE `EventEntry`='41';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 3 - Puerto de Tramo del Sol COMPLETA' WHERE `EventEntry`='42';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 3b - Reconstruyendo el Yunque y la Forja' WHERE `EventEntry`='43';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 3b - Reconstruyendo el Yunque y la Forja COMPLETA' WHERE `EventEntry`='44';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 4A - Creando el Laboratorio de Alquímia' WHERE `EventEntry`='45';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 4A - Creando el Laboratorio de Alquímia COMPLETA' WHERE `EventEntry`='46';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 4B - Construyendo el Monumento a los Caídos' WHERE `EventEntry`='47';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 4B - Construyendo el Monumento a los Caídos COMPLETA' WHERE `EventEntry`='48';
UPDATE `game_event` SET `description`='Ofensiva del Sol Devastado: Fase 4 - COMPLETA' WHERE `EventEntry`='49';
UPDATE `game_event` SET `description`='La Defensa de la Alianza de Conquista del Invierno' WHERE `EventEntry`='50';
UPDATE `game_event` SET `description`='La Defensa de la Horda de Conquista del Invierno' WHERE `EventEntry`='51';
UPDATE `game_event` SET `description`='Festival de Invierno: Regalos' WHERE `EventEntry`='54';
UPDATE `game_event` SET `description`='Se busca: La gema de alma del exarca' WHERE `EventEntry`='100';
UPDATE `game_event` SET `description`='Se busca: Fusta de montar de Nazan' WHERE `EventEntry`='101';
UPDATE `game_event` SET `description`='Se busca: El amuleto maravilloso de Shaffar' WHERE `EventEntry`='102';
UPDATE `game_event` SET `description`='Se busca: La cabeza del cazador de Época' WHERE `EventEntry`='103';
UPDATE `game_event` SET `description`='Se busca: Las plumas del tocado de Ikiss' WHERE `EventEntry`='104';
UPDATE `game_event` SET `description`='Se busca: El susurro de Murmullo' WHERE `EventEntry`='105';
UPDATE `game_event` SET `description`='Se busca: El pergamino de Cieloriss' WHERE `EventEntry`='106';
UPDATE `game_event` SET `description`='Se busca: El báculo con plumas de Keli\'dan' WHERE `EventEntry`='107';
UPDATE `game_event` SET `description`='Se busca: El proyector de Pathaleon' WHERE `EventEntry`='108';
UPDATE `game_event` SET `description`='Se busca: El corazón de Quagmirran' WHERE `EventEntry`='109';
UPDATE `game_event` SET `description`='Se busca: El Tratado del Señor de la Guerra' WHERE `EventEntry`='110';
UPDATE `game_event` SET `description`='Se busca: Un huevo de acechadora negra' WHERE `EventEntry`='111';
UPDATE `game_event` SET `description`='Se busca: El reloj de Arena de Aeonus' WHERE `EventEntry`='112';
UPDATE `game_event` SET `description`='Se busca: Un esqueje de disidente de distorsión' WHERE `EventEntry`='113';
UPDATE `game_event` SET `description`='Se busca: El sello de Garrafilada' WHERE `EventEntry`='114';
UPDATE `game_event` SET `description`='Se busca: El sello del príncipe Kael\'thas' WHERE `EventEntry`='115';
UPDATE `game_event` SET `description`='Se busca: Mirmidones Colmillo Torcido' WHERE `EventEntry`='116';
UPDATE `game_event` SET `description`='Se busca: Centuriones Mano Destrozada' WHERE `EventEntry`='117';
UPDATE `game_event` SET `description`='Se busca: Destructores de Forja de Tempestad' WHERE `EventEntry`='118';
UPDATE `game_event` SET `description`='Se busca: Canalizadores Buscasol' WHERE `EventEntry`='119';
UPDATE `game_event` SET `description`='Se busca: Señores de la falla' WHERE `EventEntry`='120';
UPDATE `game_event` SET `description`='Se busca: Centinelas de Arcatraz' WHERE `EventEntry`='121';
UPDATE `game_event` SET `description`='Se busca: Instructoras maliciosas' WHERE `EventEntry`='122';
UPDATE `game_event` SET `description`='Se busca: Hermanas del Tormento' WHERE `EventEntry`='123';
UPDATE `game_event` SET `description`='Llamamiento a las armas: Playa de los Ancestros' WHERE `EventEntry`='124';
UPDATE `game_event` SET `description`='Llamamiento a las armas: Isla de la Conquista' WHERE `EventEntry`='125';
UPDATE `game_event` SET `description`='Arenas Temporada 3' WHERE `EventEntry`='126';
UPDATE `game_event` SET `description`='Arenas Temporada 4' WHERE `EventEntry`='127';
UPDATE `game_event` SET `description`='Arenas Temporada 5' WHERE `EventEntry`='128';
UPDATE `game_event` SET `description`='Arenas Temporada 6' WHERE `EventEntry`='129';
UPDATE `game_event` SET `description`='Arenas Temporada 7' WHERE `EventEntry`='130';
UPDATE `game_event` SET `description`='Arenas Temporada 8' WHERE `EventEntry`='131';
