-- ============================ --
--   PSDB [vehicle_accessory]   --
-- ============================ --

ALTER TABLE `vehicle_accessory` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

UPDATE `vehicle_accessory` SET `description`='Destrero de la muerte de Acherus' WHERE `guid`=28782 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Máquina de asedio de Conquista del Invierno' WHERE `guid`=28312 AND `seat_id`=7;
UPDATE `vehicle_accessory` SET `description`='Máquina de asedio de Conquista del Invierno' WHERE `guid`=32627 AND `seat_id`=7;
UPDATE `vehicle_accessory` SET `description`='Kologarn' WHERE `guid`=32930 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Kologarn' WHERE `guid`=32930 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Demoledor recuperado' WHERE `guid`=33109 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Máquina de asedio recuperada' WHERE `guid`=33060 AND `seat_id`=7;
UPDATE `vehicle_accessory` SET `description`='Leviatán de llamas' WHERE `guid`=33113 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Leviatán de llamas' WHERE `guid`=33113 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Leviatán de llamas' WHERE `guid`=33113 AND `seat_id`=2;
UPDATE `vehicle_accessory` SET `description`='Leviatán de llamas' WHERE `guid`=33113 AND `seat_id`=3;
UPDATE `vehicle_accessory` SET `description`='Leviatán de llamas' WHERE `guid`=33113 AND `seat_id`=7;
UPDATE `vehicle_accessory` SET `description`='Profesor Putricidio' WHERE `guid`=36678 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Mecacóptero 304-A' WHERE `guid`=33214 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Montura del mariscal Jacob Alerius' WHERE `guid`=35637 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Ambrose Chisparrayo' WHERE `guid`=35633 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Colosos' WHERE `guid`=35768 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Jaelyne Unicanto' WHERE `guid`=34658 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Lana Martillotenaz' WHERE `guid`=35636 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Mokra el Trituracráneos' WHERE `guid`=35638 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Eressea Cantoalba' WHERE `guid`=35635 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Runok Ferocrín' WHERE `guid`=35640 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura de Zul\'tore' WHERE `guid`=35641 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Montura del mortacechador Visceri' WHERE `guid`=35634 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Grifo resucitado' WHERE `guid`=27241 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Grifo de Hibergarde' WHERE `guid`=27661 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Raptor de Drakuru' WHERE `guid`=29698 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Hipogrifo de torneo' WHERE `guid`=33778 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Yertafauce' WHERE `guid`=33687 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Yertafauce' WHERE `guid`=33687 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Yertafauce' WHERE `guid`=33687 AND `seat_id`=2;
UPDATE `vehicle_accessory` SET `description`='Protodraco de El Encuentro Hyldnir' WHERE `guid`=29625 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Protodraco de Jotunheim' WHERE `guid`=30330 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Avión de caza Rompecielo' WHERE `guid`=32189 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Profesor Putricidio' WHERE `guid`=36678 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Mamut de tundra de viajero' WHERE `guid`=32640 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Mamut de tundra de viajero' WHERE `guid`=32640 AND `seat_id`=2;
UPDATE `vehicle_accessory` SET `description`='Mamut de tundra de viajero' WHERE `guid`=32633 AND `seat_id`=1;
UPDATE `vehicle_accessory` SET `description`='Mamut de tundra de viajero' WHERE `guid`=32633 AND `seat_id`=2;
UPDATE `vehicle_accessory` SET `description`='Ingeniero del Demoledor Llavestruendo' WHERE `guid`=33669 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Zapador goblin' WHERE `guid`=29555 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Thiassi el Liberador de Rayos' WHERE `guid`=28018 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Suertudo Wilhelm' WHERE `guid`=28054 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Lobo de Orgrimmar' WHERE `guid`=33409 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Kodo de Cima del Trueno' WHERE `guid`=33300 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Carnero de Forjaz' WHERE `guid`=33408 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Mecazancudo de Gnomeregan' WHERE `guid`=33301 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Caballo de guerra Renegado' WHERE `guid`=33414 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Corcel de Ventormenta' WHERE `guid`=33297 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Elekk de El Exodar' WHERE `guid`=33416 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Sable de la noche darnassiano' WHERE `guid`=33298 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Elekk de El Exodar' WHERE `guid`=33318 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Sable de la noche darnassiano' WHERE `guid`=33319 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Carnero de Forjaz' WHERE `guid`=33316 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Mecazancudo de Gnomeregan' WHERE `guid`=33317 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Corcel de Ventormenta' WHERE `guid`=33217 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Caballo de guerra Renegado' WHERE `guid`=33324 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Kodo de Cima del Trueno' WHERE `guid`=33322 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Lobo de Orgrimmar' WHERE `guid`=33320 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Halcón zancudo de Lunargenta' WHERE `guid`=33323 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Raptor Lanza Negra' WHERE `guid`=33321 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Halcón zancudo de Lunargenta' WHERE `guid`=33418 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Raptor Lanza Negra' WHERE `guid`=33299 AND `seat_id`=0;
UPDATE `vehicle_accessory` SET `description`='Grifo esquelético del Caballero Negro' WHERE `guid`=35491 AND `seat_id`=0;
